### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by mheppner** [sloria/read_env#1]
I'm actually using sloria/environs, but the stacktrace I'm getting is coming from here. Please let me know if I should move this issue.

I'm trying to use an `environs` to read an `.env` file that contains emojis. Using Python 3.6, I get the following exception:

```
 File "/var/app/settings.py", line 17, in <module>
    env.read_env(env_path)
  File "/var/app/env/lib/python3.6/site-packages/environs.py", line 151, in read_env
    return _read_env(path=path)
  File "/var/app/env/lib/python3.6/site-packages/read_env.py", line 43, in read_env
    content = fp.read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 237: ordinal not in range(128)
```

**Comment by sloria** [comment]
Thanks @mheppner for reporting. I was not able to reproduce this in the tests. Can you post an example of a `.env` file that causes this error?

**Comment by mheppner** [comment]
Yes, you are correct...I now see what happened. I was running this on FreeBSD, where the shell's `LANG` is set to the `C` locale. When I changed my shell to `LANG=en_US.UTF-8`, environs worked as expected. I never knew that the shell's lang/locale also affected how vi/vim and Python interpret unicode. Sorry! Also, environs is a great library and I've been using it everywhere, so thank you :)

**Comment by sloria** [comment]
Glad you found the issue. And thank you for the kind words!
